app/basic_pgs/routes.py
#* routes for basic pgs ------------------------------------------------------------------------------------------------------------------------
from flask import Blueprint, render_template, redirect, send_file
# cache caused issues with static files
from flask_cachecontrol import dont_cache

blueprint = Blueprint('basic_pgs', __name__)

# root 
@blueprint.route('/')
# create route decorator
@blueprint.route('/welcome')
@blueprint.route('/home')
def index():
  return render_template('basic_pgs/index.html',  title="Welcome!")

# create route decorator
@blueprint.route('/about')
def about():
  return render_template('basic_pgs/about.html',  title="About")

# create redirect route decorator
@blueprint.route('/inspiration')
def inspiration():
  return redirect('https://unsplash.com/s/photos/satellite-imagery')

# placeholder for download file
@blueprint.route('/learn-more')
def learn():
  return redirect('https://gisgeography.com/how-to-download-sentinel-satellite-data/')

app/dynamic_pgs/routes.py
#* routes for dynamics pgs >> user specific content >> linked to db ------------------------------------------------------------------------------------------------------------------------
# for routes
from flask import Blueprint, redirect, render_template, flash, request, redirect, url_for
# models of db
from .models import Users, BlogPosts
from app.extensions.database import db
from sqlalchemy import desc, true
from slugify import slugify
# flask forms + login
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, ValidationError, TextAreaField, FileField
from wtforms.validators import DataRequired, EqualTo, Length
from wtforms.widgets import TextArea
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
# for file size check
import os

#! AWS S3 ------------------------------------------------------------------------------------------------------------------------
# postgressql does not support blobs, so AWS S3 is used to store imgs & generate img url which is stored in db
from app.config import S3_KEY, S3_SECRET, S3_LOCATION, S3BASEURL, S3_BUCKET, ALLOWED_EXTENSIONS
import boto3
s3_client = boto3.client('s3', 
  aws_access_key_id=S3_KEY,
   aws_secret_access_key=S3_SECRET,
   region_name=S3_LOCATION
   )

#*AWS S3 for blog post images
# store img from AWS S3 Bucket
def s3_upload(data, name):
  try:
    upload_file_response = s3_client.put_object(Body=data,
                                             Bucket=S3_BUCKET,
                                             Key=name,
                                             ContentType='image/jpeg')
    print(f" ** Response - {upload_file_response}")
  except Exception as e:
        print("Something Happened: ", e)
        return e

# delete img from AWS S3 Bucket
def s3_remove(name):
  try:
    delete_file_response = s3_client.delete_object(
                                              Bucket=S3_BUCKET,
                                              Key=name)
    print(f" ** Response - {delete_file_response}")
  except Exception as e:
          print("Something Happened: ", e)
          return e

# to try ensure only an img file is submitted
def allowed_img_type(image_type):
  if not "." in image_type:
    return False

  ext = image_type.rsplit(".", 1)[1]

  if ext.lower() in ALLOWED_EXTENSIONS:
    return True
  else:
    return False
  

# todo: log errors? flash & error msgs must be fixed - issues on redirect url_for

blueprint = Blueprint('dynamic_pgs', __name__)

#! create forms class ------------------------------------------------------------------------------------------------------------------------

#* form for creating a user
class SignUpForm(FlaskForm):
    user_name = StringField("Username:", validators=[DataRequired(message="Please provide a unique username."), Length(min=3, max=128, message="Username can only be between 5 and 128 characters.")])
    file = FileField("Choose a Profile Picture", validators=[DataRequired(message="This is a visual site, an image is required for your profile.")])
    bio = TextAreaField("Short Bio:")
    password_hash = PasswordField('Password:', validators=[DataRequired(message="Please create a strong password."), EqualTo('password_hash_confirm', message='Passwords must match.'), Length(min=6, max=128, message="Password must be at least 6 characters long.")])
    password_hash_confirm = PasswordField('Confirm Password:', validators=[DataRequired(message="You must retype your password.")])

    submit = SubmitField("Submit")

#* form for creating a post
class PostForm(FlaskForm):
    file = FileField("File Please", validators=[DataRequired(message="This is a visual site, an image is required for your post.")])
    title = StringField("Title", validators=[DataRequired(message="Please provide a unique title."), Length(min=3, max=128, message="Username can only be between 5 and 128 characters.")])
    description = StringField("Description", validators=[DataRequired(), Length(min=3, max=128, message="The post description must be between 3 and 128 characters long.")], widget=TextArea())
    submit = SubmitField("Submit")
   
#* form for login
class LoginForm(FlaskForm):
    user_name = StringField("Username:", validators=[DataRequired(message="Please enter your username.")])
    password = PasswordField('Password:', validators=[DataRequired(message="Please enter your password"), EqualTo('password_hash_confirm', message='Passwords must match.')])
    submit = SubmitField("Submit")

#! user signup related ------------------------------------------------------------------------------------------------------------------------

# add db record
@blueprint.route('/signup', methods=["GET", "POST"])
def signup():
  user_name = None
  form = SignUpForm()

  if form.validate_on_submit():
    image = request.files['file']
    if image.filename == "":
      flash("File must have a name.")
      return redirect(request.url)
    if not allowed_img_type(image.filename):
      flash("That file format is not supported. Try png, jpg or jpeg.")
      return redirect(request.url)
    else:
      user = Users.query.filter_by(user_name=form.user_name.data).first()
      if user is None:
        try:
          # postgressql does not support blobs, so AWS S3 is used to store imgs & generate img url which is stored in db
          s3_upload(form.file.data, form.user_name.data)
          hashed_pw = generate_password_hash(form.password_hash.data, "sha256")
          user = Users(user_name=form.user_name.data, profile_pic=S3BASEURL+form.user_name.data, bio=form.bio.data, password_hash=hashed_pw)
          db.session.add(user)
          db.session.commit()
          return redirect(url_for('dynamic_pgs.dashboard'))

        except:
            flash("Username already exists")
            return redirect(url_for('dynamic_pgs.signup'))
      
    # clear the form
    form.user_name.data = ''
    form.bio.data = ''
    form.password_hash.data = ''
  return render_template('user_pgs/signup.html', title='Sign-Up', user_name=user_name, form=form)

#* update db record
@blueprint.route('/update/<slug>/<int:id>', methods=["GET", "POST"])
@login_required
def update(id, slug):
  form = SignUpForm()
  update_user_info = Users.query.get_or_404(id)
  form.user_name.data = update_user_info.user_name
  form.bio.data = update_user_info.bio
  flash('Remember, if you forget your password, you will need to email the site admin at stacey.kenny@code.berlin')

  if request.method == "POST":
    update_user_info.user_name = request.form['user_name']
    update_user_info.bio = request.form['bio']
    update_user_info.slug = slugify(request.form['user_name'])

    try:
      db.session.commit()
      flash("Your details are Updated!")
      return redirect(url_for('dynamic_pgs.dashboard'))

    except:
      return redirect(url_for('dynamic_pgs.dashboard'))
  
  else:
    return render_template('user_pgs/update.html', title='Update Details', form=form, update_user_info=update_user_info, id=id, slug=slug)

#* delete db record
@blueprint.route('/delete/<slug>/<int:id>')
@login_required
def delete(id, slug):
  user_name = None
  form = SignUpForm()
  delete_user_info = Users.query.get_or_404(id)

  try: 
    db.session.delete(delete_user_info)
    db.session.commit()
    flash("User Deleted Successfully.")
    return redirect(url_for('dynamic_pgs.signup'))

  except:
    flash("Hmmm... Something did not work. Try again later.")
    return render_template('user_pgs/signup.html', title='Delete User', user_name=user_name, form=form, delete_user_info=delete_user_info, id=id, slug=slug)

#* login pg
@blueprint.route('/login', methods=["GET", "POST"])
def login():
  form = LoginForm()
  flash('Remember, if you forget your password, you will need to email the site admin at stacey.kenny@code.berlin')
  user = Users.query.filter_by(user_name=form.user_name.data).first()
  if not user or not check_password_hash(user.password_hash, form.password.data):
    return render_template('user_pgs/login.html', title='Login', form=form)
  login_user(user)
  return redirect(url_for('dynamic_pgs.dashboard'))

@blueprint.get('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('dynamic_pgs.login'))

# dashboard
@blueprint.route('/dashboard', methods=["GET", "POST"])
@login_required
def dashboard():
  return render_template('user_pgs/dashboard.html', title='User Dashboard')

#! blog post related ------------------------------------------------------------------------------------------------------------------------
# create a post
@blueprint.route('/gisart-gallery/create', methods=["GET", "POST"])
@login_required
def create_post():
  form = PostForm()
  
  if form.validate_on_submit():
    image = request.files['file']
    if image.filename == "":
      flash("File must have a name.")
      return redirect(request.url)
    if not allowed_img_type(image.filename):
      flash("That file format is not supported. Try png, jpg or jpeg.")
      return redirect(request.url)
    # postgressql does not support blobs, so AWS S3 is used to store imgs & generate img url which is stored in db
    s3_upload(form.file.data, form.title.data)
    # one-to-many relationship
    author = current_user.id
    post = BlogPosts(title=form.title.data, image=S3BASEURL+form.title.data, description=form.description.data, author_id=author)

    db.session.add(post)
    db.session.commit()

    # clear the form
    form.title.data = ''
    form.description.data = ''
    flash("Post successfully created!")
    return redirect(url_for('dynamic_pgs.view_posts'))
      
  return render_template('blog_post_pgs/create_post.html', title='Share Your GISart', form=form)


#*view all posts
@blueprint.route('/gisart-gallery/view')
def view_posts():
  # collect posts from db
  posts = BlogPosts.query.order_by(BlogPosts.date_posted.desc())

app/templates/components/flash_msgs.html
{% for message in get_flashed_messages() %}
<div
  id="alert"
  class="alert alert-secondary alert-dismissible fade show"
  role="alert"
>
  {{ message }}
  <button
    type="button"
    class="btn-close"
    data-bs-dismiss="alert"
    aria-label="Close"
  ></button>
</div>
{% endfor %}

app/templates/components/footer.html
<footer class="mt-auto text-white-50">
  <small class="text-muted credit">
    Photo by
    <a
      href="https://unsplash.com/@spacex?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
      >SpaceX</a
    >
    on
    <a
      href="https://unsplash.com/s/photos/spacex?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
      >Unsplash</a
    >
  </small>
  {% if current_user.is_authenticated %}
  <small>
    Logged in as {{ current_user.user_name }}. {% if current_user.id == 1 %}
    <a href="{{ url_for('dynamic_pgs.admin') }}">Admin</a> | {% endif %}
    <a href="{{ url_for('dynamic_pgs.dashboard') }}">Dashboard</a> |
    <a href="{{ url_for('dynamic_pgs.logout') }}">Logout</a>
  </small>
  {% else %}
  <small>
    <a class="navbar-text hover-line" href="{{ url_for('dynamic_pgs.signup') }}"
      >Sign-up</a
    >
    |
    <a
      <a
      class="navbar-text hover-line"
      href="{{ url_for('dynamic_pgs.login') }}"
      >Login</a
    >
  </small>
  {% endif %}
</footer>

app/templates/components/hero.html
<section id="hero" class="container parent spacer">
  <div class="child staggering">
    {% block title %}
    <h1 class="title-pg slide-rtl text-fade-in">GISart</h1>
    {% endblock %} {% if current_user.is_authenticated %}
    <p class="slide-ltr el">
      <a class="hover-line" href="{{ url_for('basic_pgs.about') }}"
        >Learn More</a
      >
    </p>
    <p class="slide-ltr el">
      <a
        class="nav-link hover-line"
        href="{{ url_for('dynamic_pgs.dashboard') }}"
        >dashboard</a
      >
    </p>

    {% else %}
    <p class="slide-ltr el">
      <a class="hover-line" href="{{ url_for('basic_pgs.about') }}"
        >Learn More</a
      >
    </p>
    <p class="slide-ltr el">
      <a class="hover-line" href="{{ url_for('dynamic_pgs.signup') }}"
        >Sign-up</a
      >
    </p>
    <p class="slide-ltr el">
      <a class="hover-line" href="{{ url_for('dynamic_pgs.login') }}">Login</a>
    </p>
    {% endif %}
  </div>
</section>
<small class="text-muted hero-credit">
  Photo by
  <a
    href="https://unsplash.com/@spacex?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
    >SpaceX</a
  >
  on
  <a
    href="https://unsplash.com/s/photos/spacex?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
    >Unsplash</a
  >
</small>

<div class="img-bg">
  <img
    type="image/png"
    src="{{url_for('static', filename='images/spacex-dark.png')}}"
    alt="SpaceX image of late day or night sky and time lapse light line from ascending rocket."
  />
</div>

app/templates/components/navbar.html
<!-- ! neu ////// -->
<nav class="navbar navbar-expand-lg navbar-dark sticky-top" aria-label="Navbar">
  <div class="container-fluid">
    <a class="navbar-brand text-fade-in" href="{{ url_for('basic_pgs.index') }}"
      >GISart</a
    >
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a
            class="nav-link hover-line"
            href="{{ url_for('basic_pgs.about') }}"
            aria-label="About page link"
            >About</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link hover-line"
            href="{{ url_for('basic_pgs.learn') }}"
            target="_blank"
            aria-label="External link"
            >Learn How</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link hover-line"
            href="{{ url_for('dynamic_pgs.view_posts') }}"
            aria-label="View all posts"
            >View</a
          >
        </li>
        {% if current_user.is_authenticated %}
        <li class="nav-item dropdown">
          <a
            class="nav-link dropdown-toggle"
            href="#"
            id="navbarDropdown"
            role="button"
            data-bs-toggle="dropdown"
            aria-expanded="false"
          >
            For Users
          </a>
          <ul
            class="dropdown-menu dropdown-menu-dark"
            aria-labelledby="navbarDropdown"
          >
            <li>
              <a
                class="dropdown-item hover-line"
                href="{{ url_for('dynamic_pgs.create_post') }}"
                aria-label="Share a post"
                >Share</a
              >
            </li>
            <li>
              <a
                class="dropdown-item hover-line"
                href="{{ url_for('dynamic_pgs.dashboard') }}"
                aria-label="User dashboard"
                >Dashboard</a
              >
            </li>
            <li><hr class="dropdown-divider" /></li>
            <li>
              <small>
                <a
                  id="logout-link"
                  class="dropdown-item hover-line"
                  href="{{ url_for('dynamic_pgs.logout') }}"
                  aria-label="Logout"
                  >Logout</a
                >
              </small>
            </li>
            {% if current_user.id == 1 %}
            <li><hr class="dropdown-divider" /></li>
            <li>
              <a
                class="dropdown-item hover-line"
                href="{{ url_for('dynamic_pgs.admin') }}"
                >Admin</a
              >
            </li>
            {% endif %}{% endif %}
          </ul>
        </li>
        {% if current_user.is_authenticated %} {% else %}
        <!-- * signup & login only seen if session is unauthenticated -->
        <a
          id="signup-link"
          class="nav-link hover-line"
          href="{{ url_for('dynamic_pgs.signup') }}"
          aria-label="Sign-up"
          >Sign-up</a
        >
        |
        <a
          id="login-link"
          class="nav-link hover-line"
          href="{{ url_for('dynamic_pgs.login') }}"
          aria-label="Login"
          >Login</a
        >
        {% endif %}
      </ul>
    </div>
  </div>
</nav>