app/basic_pgs/routes.py
#* routes for basic pgs ------------------------------------------------------------------------------------------------------------------------
from flask import Blueprint, render_template, redirect, send_file
# cache caused issues with static files
from flask_cachecontrol import dont_cache

blueprint = Blueprint('basic_pgs', __name__)

# root 
@blueprint.route('/')
# create route decorator
@blueprint.route('/welcome')
@blueprint.route('/home')
def index():
  return render_template('basic_pgs/index.html',  title="Welcome!")

# create route decorator
@blueprint.route('/about')
def about():
  return render_template('basic_pgs/about.html',  title="About")

# create redirect route decorator
@blueprint.route('/inspiration')
def inspiration():
  return redirect('https://unsplash.com/s/photos/satellite-imagery')

# placeholder for download file
@blueprint.route('/learn-more')
def learn():
  return redirect('https://gisgeography.com/how-to-download-sentinel-satellite-data/')

app/dynamic_pgs/routes.py
#* routes for dynamics pgs >> user specific content >> linked to db ------------------------------------------------------------------------------------------------------------------------
# for routes
from flask import Blueprint, redirect, render_template, flash, request, redirect, url_for
# models of db
from .models import Users, BlogPosts
from app.extensions.database import db
from sqlalchemy import desc, true
from slugify import slugify
# flask forms + login
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField, ValidationError, TextAreaField, FileField
from wtforms.validators import DataRequired, EqualTo, Length
from wtforms.widgets import TextArea
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
# for file size check
import os

#! AWS S3 ------------------------------------------------------------------------------------------------------------------------
# postgressql does not support blobs, so AWS S3 is used to store imgs & generate img url which is stored in db
from app.config import S3_KEY, S3_SECRET, S3_LOCATION, S3BASEURL, S3_BUCKET, ALLOWED_EXTENSIONS
import boto3
s3_client = boto3.client('s3', 
  aws_access_key_id=S3_KEY,
   aws_secret_access_key=S3_SECRET,
   region_name=S3_LOCATION
   )

#*AWS S3 for blog post images
# store img from AWS S3 Bucket
def s3_upload(data, name):
  try:
    upload_file_response = s3_client.put_object(Body=data,
                                             Bucket=S3_BUCKET,
                                             Key=name,
                                             ContentType='image/jpeg')
    print(f" ** Response - {upload_file_response}")
  except Exception as e:
        print("Something Happened: ", e)
        return e

# delete img from AWS S3 Bucket
def s3_remove(name):
  try:
    delete_file_response = s3_client.delete_object(
                                              Bucket=S3_BUCKET,
                                              Key=name)
    print(f" ** Response - {delete_file_response}")
  except Exception as e:
          print("Something Happened: ", e)
          return e

# to try ensure only an img file is submitted
def allowed_img_type(image_type):
  if not "." in image_type:
    return False

  ext = image_type.rsplit(".", 1)[1]

  if ext.lower() in ALLOWED_EXTENSIONS:
    return True
  else:
    return False
  

# todo: log errors? flash & error msgs must be fixed - issues on redirect url_for

blueprint = Blueprint('dynamic_pgs', __name__)

#! create forms class ------------------------------------------------------------------------------------------------------------------------

#* form for creating a user
class SignUpForm(FlaskForm):
    user_name = StringField("Username:", validators=[DataRequired(message="Please provide a unique username."), Length(min=3, max=128, message="Username can only be between 5 and 128 characters.")])
    file = FileField("Choose a Profile Picture", validators=[DataRequired(message="This is a visual site, an image is required for your profile.")])
    bio = TextAreaField("Short Bio:")
    password_hash = PasswordField('Password:', validators=[DataRequired(message="Please create a strong password."), EqualTo('password_hash_confirm', message='Passwords must match.'), Length(min=6, max=128, message="Password must be at least 6 characters long.")])
    password_hash_confirm = PasswordField('Confirm Password:', validators=[DataRequired(message="You must retype your password.")])

    submit = SubmitField("Submit")

#* form for creating a post
class PostForm(FlaskForm):
    file = FileField("File Please", validators=[DataRequired(message="This is a visual site, an image is required for your post.")])
    title = StringField("Title", validators=[DataRequired(message="Please provide a unique title."), Length(min=3, max=128, message="Username can only be between 5 and 128 characters.")])
    description = StringField("Description", validators=[DataRequired(), Length(min=3, max=128, message="The post description must be between 3 and 128 characters long.")], widget=TextArea())
    submit = SubmitField("Submit")
   
#* form for login
class LoginForm(FlaskForm):
    user_name = StringField("Username:", validators=[DataRequired(message="Please enter your username.")])
    password = PasswordField('Password:', validators=[DataRequired(message="Please enter your password"), EqualTo('password_hash_confirm', message='Passwords must match.')])
    submit = SubmitField("Submit")

#! user signup related ------------------------------------------------------------------------------------------------------------------------

# add db record
@blueprint.route('/signup', methods=["GET", "POST"])
def signup():
  user_name = None
  form = SignUpForm()

  if form.validate_on_submit():
    image = request.files['file']
    if image.filename == "":
      flash("File must have a name.")
      return redirect(request.url)
    if not allowed_img_type(image.filename):
      flash("That file format is not supported. Try png, jpg or jpeg.")
      return redirect(request.url)
    else:
      user = Users.query.filter_by(user_name=form.user_name.data).first()
      if user is None:
        try:
          # postgressql does not support blobs, so AWS S3 is used to store imgs & generate img url which is stored in db
          s3_upload(form.file.data, form.user_name.data)
          hashed_pw = generate_password_hash(form.password_hash.data, "sha256")
          user = Users(user_name=form.user_name.data, profile_pic=S3BASEURL+form.user_name.data, bio=form.bio.data, password_hash=hashed_pw)
          db.session.add(user)
          db.session.commit()
          return redirect(url_for('dynamic_pgs.dashboard'))

        except:
            flash("Username already exists")
            return redirect(url_for('dynamic_pgs.signup'))
      
    # clear the form
    form.user_name.data = ''
    form.bio.data = ''
    form.password_hash.data = ''
  return render_template('user_pgs/signup.html', title='Sign-Up', user_name=user_name, form=form)

#* update db record
@blueprint.route('/update/<slug>/<int:id>', methods=["GET", "POST"])
@login_required
def update(id, slug):
  form = SignUpForm()
  update_user_info = Users.query.get_or_404(id)
  form.user_name.data = update_user_info.user_name
  form.bio.data = update_user_info.bio
  flash('Remember, if you forget your password, you will need to email the site admin at stacey.kenny@code.berlin')

  if request.method == "POST":
    update_user_info.user_name = request.form['user_name']
    update_user_info.bio = request.form['bio']
    update_user_info.slug = slugify(request.form['user_name'])

    try:
      db.session.commit()
      flash("Your details are Updated!")
      return redirect(url_for('dynamic_pgs.dashboard'))

    except:
      return redirect(url_for('dynamic_pgs.dashboard'))
  
  else:
    return render_template('user_pgs/update.html', title='Update Details', form=form, update_user_info=update_user_info, id=id, slug=slug)

#* delete db record
@blueprint.route('/delete/<slug>/<int:id>')
@login_required
def delete(id, slug):
  user_name = None
  form = SignUpForm()
  delete_user_info = Users.query.get_or_404(id)

  try: 
    db.session.delete(delete_user_info)
    db.session.commit()
    flash("User Deleted Successfully.")
    return redirect(url_for('dynamic_pgs.signup'))

  except:
    flash("Hmmm... Something did not work. Try again later.")
    return render_template('user_pgs/signup.html', title='Delete User', user_name=user_name, form=form, delete_user_info=delete_user_info, id=id, slug=slug)

#* login pg
@blueprint.route('/login', methods=["GET", "POST"])
def login():
  form = LoginForm()
  flash('Remember, if you forget your password, you will need to email the site admin at stacey.kenny@code.berlin')
  user = Users.query.filter_by(user_name=form.user_name.data).first()
  if not user or not check_password_hash(user.password_hash, form.password.data):
    return render_template('user_pgs/login.html', title='Login', form=form)
  login_user(user)
  return redirect(url_for('dynamic_pgs.dashboard'))

@blueprint.get('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('dynamic_pgs.login'))

# dashboard
@blueprint.route('/dashboard', methods=["GET", "POST"])
@login_required
def dashboard():
  return render_template('user_pgs/dashboard.html', title='User Dashboard')

#! blog post related ------------------------------------------------------------------------------------------------------------------------
# create a post
@blueprint.route('/gisart-gallery/create', methods=["GET", "POST"])
@login_required
def create_post():
  form = PostForm()
  
  if form.validate_on_submit():
    image = request.files['file']
    if image.filename == "":
      flash("File must have a name.")
      return redirect(request.url)
    if not allowed_img_type(image.filename):
      flash("That file format is not supported. Try png, jpg or jpeg.")
      return redirect(request.url)
    # postgressql does not support blobs, so AWS S3 is used to store imgs & generate img url which is stored in db
    s3_upload(form.file.data, form.title.data)
    # one-to-many relationship
    author = current_user.id
    post = BlogPosts(title=form.title.data, image=S3BASEURL+form.title.data, description=form.description.data, author_id=author)

    db.session.add(post)
    db.session.commit()

    # clear the form
    form.title.data = ''
    form.description.data = ''
    flash("Post successfully created!")
    return redirect(url_for('dynamic_pgs.view_posts'))
      
  return render_template('blog_post_pgs/create_post.html', title='Share Your GISart', form=form)


#*view all posts
@blueprint.route('/gisart-gallery/view')
def view_posts():
  # collect posts from db
  posts = BlogPosts.query.order_by(BlogPosts.date_posted.desc())

app/templates/user_pgs/dashboard.html
{% extends 'base.html' %}
<!-- add navbar component -->
{% block body %}{% include 'components/navbar.html' %}
<section class="container spacer">
  {% include 'components/flash_msgs.html' %}
  <!-- locking down page -->
  {% if current_user.is_authenticated %}
  <div class="container">
    <div class="row gutters-row justify-content-center">
      <div class="col-sm-auto gutters-col justify-content-center">
        <div
          class="card text-center bg-dark text-white max-width"
          aria-label="User profile card"
        >
          <div class="card-header profile-picture">
            <img
              type="image/png"
              src="{{ current_user.profile_pic }}"
              alt="{{ current_user.user_name }}'s Display Picture."
              class="card-img-top profile-picture"
            />
          </div>
          <div class="card-body">
            <h5 class="card-title">{{ current_user.user_name|capitalize }}</h5>
            <p class="card-text">{{ current_user.bio }}</p>
          </div>
          <div class="card-footer">
            <h6 class="text-muted">
              Member Since: {{ current_user.date_added.date() }}
            </h6>
          </div>
        </div>
      </div>
      <div class="col-lg-auto gutters-col d-flex justify-content-center">
        <div class="card bg-dark text-white max-width">
          <div class="card-body">
            <h4 class="card-title welcome-user">
              Welcome {{ current_user.user_name|capitalize }}
            </h4>
            <p class="card-text text-center">Here are some quick links:</p>
            <div class="d-flex justify-content-center">
              <a
                class="btn btn-primary text-dark btn-sm"
                href="{{ url_for('dynamic_pgs.create_post') }}"
                aria-label="Share a post"
                >Share</a
              >
            </div>
            <div class="d-flex justify-content-center">
              <a
                class="btn btn-info text-dark btn-sm"
                href="{{ url_for('dynamic_pgs.view_posts') }}"
                aria-label="View all posts"
                >View All Posts</a
              >
            </div>
            <div class="d-flex justify-content-center">
              <a
                class="btn btn-warning text-dark btn-sm"
                href="{{ url_for('dynamic_pgs.update', id=current_user.id, slug=current_user.slug) }}"
                aria-label="Update profile"
                >Update Profile</a
              >
            </div>
            <br />
            <div class="d-flex justify-content-center">
              <a
                class="btn btn-danger text-dark btn-sm"
                href="{{ url_for('dynamic_pgs.delete', id=current_user.id, slug=current_user.slug) }}"
                aria-label="Delete account"
                >Delete Account</a
              >
            </div>
            <br />
            <p class="card-text text-muted text-center">
              <small>
                Unfortunately, you cannot change your password at this time, we
                are still working on this feature.</small
              >
            </p>
            <div class="d-flex justify-content-center">
              <small>
                <a
                  id="logout-link"
                  class="btn btn-secondary text-dark btn-sm"
                  href="{{ url_for('dynamic_pgs.logout') }}"
                  aria-label="Logout"
                  >Logout</a
                >
              </small>
              {% if current_user.id == 1 %}
              <a
                class="btn btn-success text-dark btn-sm"
                href="{{ url_for('dynamic_pgs.admin') }}"
                >Admin</a
              >
              {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <h6>Please login in or Signup to access this page.</h6>
  <br />
  <a class="navbar-text hover-line" href="{{ url_for('dynamic_pgs.signup') }}"
    >Sign-up</a
  >
  |
  <a <a class="navbar-text hover-line" href="{{ url_for('dynamic_pgs.login') }}"
    >Login</a
  >
  {% endif %}
</section>
<div class="img-bg">
  <img
    type="image/png"
    src="{{url_for('static', filename='images/spacex-dark.png')}}"
    alt="SpaceX image of late day or night sky and time lapse light line from ascending rocket."
  />
</div>
{% include 'components/footer.html' %} {% endblock %}

app/templates/user_pgs/login.html
{% extends 'base.html' %} {% block body %} {% include 'components/navbar.html'
%}
<section id="login" class="container form_pg spacer">
  {% include 'components/flash_msgs.html' %} {% if title %}
  <h1>{{ title }}</h1>
  {% else %}
  <h1>GISart</h1>
  {% endif %}
  <br />
  <!-- login form -->
  <form
    method="POST"
    class="flex justify-content-md-center my_form"
    aria-label="Login form"
  >
    <!--*  generates a hidden field that includes a token that is used to protect the form against CSRF attacks, becauses hackers deffo want to target this -->
    {{ form.hidden_tag() }}

    <!-- the form -->
    <!--* user name -->
    {{ form.user_name.label (class="form-label") }} {{
    form.user_name(class="form-control") }}
    <br />
    <!--* password -->
    {{ form.password.label (class="form-label") }} {{
    form.password(class="form-control") }}
    <br />
    {{ form.submit(class="btn btn-warning text-dark") }}
    <a class="btn btn-primary text-dark" href="{{ url_for('basic_pgs.about') }}"
      >Go Back</a
    >
  </form>
</section>
<div class="img-bg">
  <img
    type="image/png"
    src="{{url_for('static', filename='images/spacex-dark.png')}}"
    alt="SpaceX image of late day or night sky and time lapse light line from ascending rocket."
  />
</div>
{% include 'components/footer.html' %} {% endblock %}

app/templates/user_pgs/signup.html
{% extends 'base.html' %}
<!-- add navbar component -->
{% block body %}{% include 'components/navbar.html' %}
<section id="signup" class="container form_pg spacer">
  {% include 'components/flash_msgs.html' %} {% if title %}
  <h1>{{ title }}</h1>
  {% else %}
  <h1>GISart</h1>
  {% endif %}
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi minus
    laborum nesciunt amet animi, neque ut quas cum maxime labore quia odit
    saepe, quidem inventore vero perferendis incidunt porro tempore!
  </p>
  <br />
  <!-- signup form -->
  <form
    method="POST"
    class="flex justify-content-md-center my_form"
    enctype="multipart/form-data"
  >
    <!--  generates a hidden field that includes a token that is used to protect the form against CSRF attacks, because hackers deffo want to target this -->
    {{ form.hidden_tag() }}
    <!-- the form -->
    <!-- * user name -->
    {{ form.user_name.label (class="form-label") }} {{
    form.user_name(class="form-control") }}
    <br />
    <!-- * file  -->
    {{ form.file.label (class="form-label") }} {{
    form.file(class="form-control", accept="image/png, image/jpeg") }}
    <h5 class="pro-pic-txt">
      Be wise selecting a profile picture, much like your face, it can't be
      changed unless you're willing to pay a pro to try.
    </h5>
    <br />
    <!-- * user bio -->
    {{ form.bio.label (class="form-label") }} {{ form.bio(class="form-control")
    }}
    <br />
    <br />
    <!-- * password -->
    {{ form.password_hash.label (class="form-label") }} {{
    form.password_hash(class="form-control") }}
    <br />
    <!-- * password confirmation -->
    {{ form.password_hash_confirm.label (class="form-label") }} {{
    form.password_hash_confirm(class="form-control") }}
    <br />
    <br />
    {{ form.submit(class="btn btn-warning text-dark") }}
    <button class="btn btn-primary text-dark" onclick="history.back()">
      Go Back
    </button>
  </form>
</section>
<div class="img-bg">
  <img
    type="image/png"
    src="{{url_for('static', filename='images/spacex-dark.png')}}"
    alt="SpaceX image of late day or night sky and time lapse light line from ascending rocket."
  />
</div>
{% include 'components/footer.html' %} {% endblock %}

app/templates/user_pgs/update.html
{% extends 'base.html' %}
<!-- add navbar component -->
{% block body %}{% include 'components/navbar.html' %}
<section id="update" class="container form_pg spacer">
  {% include 'components/flash_msgs.html' %} {% if id == current_user.id %} {%
  if title %}
  <h1>{{ title }}</h1>
  {% else %}
  <h1>GISart</h1>
  {% endif %}

  <br />
  <!-- signup(update) form -->
  <form
    action="/update/{{ update_user_info.slug }}/{{ update_user_info.id }}"
    method="POST"
    class="flex justify-content-md-center my_form"
    enctype="multipart/form-data"
  >
    <!--  generates a hidden field that includes a token that is used to protect the form against CSRF attacks, becauses hackers deffo want to target this -->
    {{ form.hidden_tag() }}
    <!-- the form -->
    <!-- * user name -->
    {{ form.user_name.label (class="form-label") }} {{
    form.user_name(class="form-control", value=update_user_info.user_name) }}
    <br />
    <!-- * user bio -->
    {{ form.bio.label (class="form-label") }} {{ form.bio(class="form-control",
    value=update_user_info.bio) }}
    <br />
    <br />
    {{ form.submit(class="btn btn-warning text-dark") }}
    <a
      class="btn btn-danger text-dark"
      href="{{ url_for('dynamic_pgs.delete', id=id, slug=slug) }}"
      >Delete User</a
    >
    <a
      class="btn btn-secondary text-dark"
      href="{{ url_for('dynamic_pgs.dashboard') }}"
      aria-label="user dashboard"
    >
      Cancel</a
    >
  </form>
  {% else %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <svg
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      fill="currentColor"
      class="bi bi-exclamation-triangle-fill flex-shrink-0 me-2"
      viewBox="0 0 16 16"
      role="img"
      aria-label="Warning:"
    >
      <path
        d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"
      />
    </svg>
    Unauthorized
    <button
      type="button"
      class="btn-close"
      data-bs-dismiss="alert"
      aria-label="Close"
    ></button>
  </div>
  <h2>You are not authorized to do that.</h2>
  <button class="btn btn-secondary text-dark" onclick="history.back()">
    Go Back
  </button>
  {% endif %}
</section>
<div class="img-bg">
  <img
    type="image/png"
    src="{{url_for('static', filename='images/spacex-dark.png')}}"
    alt="SpaceX image of late day or night sky and time lapse light line from ascending rocket."
  />
</div>
{% include 'components/footer.html' %} {% endblock %}