app/basic_pgs/__init__.py
from . import routes

app/basic_pgs/routes.py
#* routes for basic pgs ------------------------------------------------------------------------------------------------------------------------
from flask import Blueprint, render_template, redirect, send_file
# cache caused issues with static files
from flask_cachecontrol import dont_cache

blueprint = Blueprint('basic_pgs', __name__)

# root 
@blueprint.route('/')
# create route decorator
@blueprint.route('/welcome')
@blueprint.route('/home')
def index():
  return render_template('basic_pgs/index.html',  title="Welcome!")

# create route decorator
@blueprint.route('/about')
def about():
  return render_template('basic_pgs/about.html',  title="About")

# create redirect route decorator
@blueprint.route('/inspiration')
def inspiration():
  return redirect('https://unsplash.com/s/photos/satellite-imagery')

# placeholder for download file
@blueprint.route('/learn-more')
def learn():
  return redirect('https://gisgeography.com/how-to-download-sentinel-satellite-data/')

app/templates/basic_pgs/about.html
{% extends 'base.html' %}
<!-- navbar component -->
{% block body %} {% include 'components/navbar.html' %}
<section id="about" class="container">
  {% if title %}
  <h1>{{ title }}</h1>
  {% else %}
  <h1>GISart</h1>
  {% endif %}
</section>
<article id="article" class="container spacer">
  <p>
    Users can upload and share satellite, remote sensing, or cartographic photos
    on this website. The USGS's photographic posts on Unsplash served as the
    site's primary source of
    <a
      class="nav-link hover-line"
      href="{{ url_for('basic_pgs.inspiration') }}"
      target="_blank"
      >inspiration</a
    >. See a few of their pictures on this page.
  </p>
  <div class="container img-container">
    <img
      type="image/png"
      src="{{url_for('static', filename='images/Kazakhstan-2.png')}}"
      alt="SpaceX image of late day or night sky and time lapse light line from ascending rocket."
      onmouseover="KazakImage1(this)"
      onmouseout="KazakImage2(this)"
    />
  </div>
  <p class="text-muted">
    <small>
      Photo by
      <a
        href="https://unsplash.com/@usgs?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
        >USGS</a
      >
      on
      <a
        href="https://unsplash.com/s/photos/satellite-imagery?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
        >Unsplash</a
      ></small
    >
  </p>
  <p>
    A geographic information system is a type of database that combines software
    tools for managing, analysing, and displaying geographic data with the
    database itself. GIS connects data to a map and combines all kinds of
    descriptive data with location data. This offers a basis for mapping and
    analysis, which are applied in science and practically every sector of the
    economy. These visualisations can be artistic as well as analytical and
    functional.
  </p>
  <div class="container img-container">
    <img
      type="image/png"
      src="{{url_for('static', filename='images/Algeria.png')}}"
      alt="SpaceX image of late day or night sky and time lapse light line from ascending rocket."
      onmouseover="algeImage1(this)"
      onmouseout="algeImage2(this)"
    />
  </div>
  <p class="text-muted">
    <small>
      Photo by
      <a
        href="https://unsplash.com/@usgs?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
        >USGS</a
      >
      on
      <a
        href="https://unsplash.com/s/photos/satellite-imagery?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText"
        >Unsplash</a
      ></small
    >
  </p>
  <p>
    Utilize the GIS tools and your creativity or curiosity to change the way we
    can see the world.
  </p>
</article>

<div class="img-bg">
  <img
    type="image/png"
    src="{{url_for('static', filename='images/spacex-dark.png')}}"
    alt="SpaceX image of late day or night sky and time lapse light line from ascending rocket."
  />
</div>
{% include 'components/footer.html' %} {% endblock %}

app/templates/basic_pgs/index.html
{% extends 'base.html' %} {% block body %}
<!--! just testing jinja 2 & components -->
<!-- add hero component -->
{% include 'components/hero.html' %} {% endblock %}